version: '3.8'

services:

  mysqldb:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB_NAME}

    ports:
      - 3307:3306

volumes:
  mysql_data:
