version: '3.8'

services:

  client:
    build:
      context: .
      dockerfile: Dockerfile.client

    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 5000:5000
    restart: always

  mysqldb:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database

    ports:
      - 3307:3306

volumes:
  mysql_data: