import { FruitsProvider } from '@/contexts/fruitsContext'
import './globals.css'
import Navbar from '@/components/Nadvar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <FruitsProvider >
          <Navbar />
          {children}
        </FruitsProvider>
      </body>
    </html>
  )
}
